chore: update Bitcoin Core and LND
ExchangeUnion/xud-docker pull request #239
Opened 2019-11-27 19:04 UTC by michael1011

Could someone with a synced testnet instance please make sure that the new LND version didn't break the swaps?

2019-12-02 12:32 UTC, ghost approved these changes

2019-12-02 16:17 UTC, kilrau requested changes

2019-12-02 16:17 UTC, kilrau commented on xud-mainnet/docker-compose.yml
> +    image: exchangeunion/lnd:0.8.1-beta
why only lndbtc? lndltc still on 0.7.1.

2019-12-02 16:17 UTC, kilrau commented on xud-testnet/docker-compose.yml
> +    image: exchangeunion/lnd:0.8.1-beta
why only lndltc? lndbtc still on 0.7.1.

2019-12-02 16:33 UTC, kilrau commented on xud-testnet/docker-compose.yml
> +    image: exchangeunion/lnd:0.8.1-beta
Can't test swaps with my testnet instance against xud1.testnet.exchangeunion.com because lndbtc needs to be upgraded to 0.8.1 too in order to support bitcoind 0.19.0.1

2019-12-02 16:41 UTC, ghost requested changes
Good catch @kilrau - we only upgraded lndbtc for mainnet and lndltc for testnet...

2019-12-02 16:44 UTC, erkarl commented
Also, should we be upgrading `exchangeunion/lnd-simnet:latest`?

2019-12-02 16:46 UTC, kilrau commented
> Also, should we be upgrading exchangeunion/lnd-simnet:latest?
Yes, we should. And test (everything should work out of the box, even though xud1,2,3 are not upgraded).

2019-12-04 15:38 UTC, erkarl commented
I think it makes sense to upgrade our simulation tests to `0.8.1` first, then simnet in a separate PR, and finally this PR.

2019-12-04 15:59 UTC, michael1011 commented
> I think it makes sense to upgrade our simulation tests to 0.8.1 first, then simnet in a separate PR, and finally this PR.

Agreed. Should I open these PRs? @erkarl @kilrau

2019-12-04 16:07 UTC, erkarl commented
@michael1011 sure, but let's wait for https://github.com/ExchangeUnion/xud/pull/1345 first to avoid merge conflicts. `xud-simnet` PR can be prepared now, though.

2019-12-04 18:24 UTC, kilrau approved these changes
What I tested:
- Upgrade my local xud-docker testnet env (bitcoind 0.18 & lnd 0.7.1, fully synced) to this branch. All good - passed.
- LTC/BTC Buy & Sell Trades between my updated local (0.19.0.1 & lnd 0.8.1) env and old xud1.testnet.exchangeunion (bitcoind 0.18 & lnd 0.7.1). All good - passed.

2019-12-04 18:28 UTC, kilrau commented
> `xud-simnet` PR can be prepared now, though.

Could you push the updated [`lnd-simnet`](https://cloud.docker.com/u/exchangeunion/repository/docker/exchangeunion/lnd-simnet) image though? That shoulnd't break anything and I can already test it.

2019-12-09 14:14 UTC, kilrau commented
https://github.com/ExchangeUnion/xud/pull/1345 is merged, let's still wait for the final lnd 0.8.2 release though.

2019-12-12 09:56 UTC, kilrau requested changes
https://github.com/lightningnetwork/lnd/releases/tag/v0.8.2-beta released, let's include it and do another round of manual testing.

2019-12-17 12:34 UTC, erkarl commented
Updated to `0.8.2`.

2019-12-18 15:04 UTC, reliveyy approved these changes

2019-12-18 15:05 UTC, merged