Add arby configuration options
ExchangeUnion/xud-docker pull request #562
Opened 2020-06-22 11:56 UTC by kilrau

This PR adds `test-centralized-baseasset-balance` and `test-centralized-quoteasset-balance`
configuration options to the arby section of the config.

These values are used as the mock centralized exchange base/quoteasset balance when arby is running in testing mode.

2020-06-23 13:35 UTC, raladev commented
- [ ] it does not work for me with last commit of arby (9e9eaa85ae8359804d31e1f09488bee1b6b6f871). I tried to use cmd params and config file, but arby log always displays other values.
[Screenshot from 2020-06-23 16-29-22](https://user-images.githubusercontent.com/29906866/85410079-4f05d100-b56f-11ea-986f-1411705f6378.png)
[Screenshot from 2020-06-23 16-29-13](https://user-images.githubusercontent.com/29906866/85410083-4f9e6780-b56f-11ea-8bf9-9741c744061e.png)
[Screenshot 2020-06-23 16:21:40](https://user-images.githubusercontent.com/29906866/85410084-5036fe00-b56f-11ea-8a64-275913146a83.png)

2020-06-23 13:38 UTC, raladev requested changes
above

2020-06-23 13:48 UTC, erkarl commented
Thanks for testing. I managed to reproduce. Will fix soon.

2020-06-24 11:28 UTC, erkarl commented
@raladev 

Should be working now. In addition, we're now printing all the configuration options in arby logs when starting (except the CEX API keys):
```
2020-06-24 11:26:34.3434 [GLOBAL] info: Starting. Hello, Arby.
2020-06-24 11:26:34.3434 [GLOBAL] info: Running with config:
LOG_LEVEL: trace
DATA_DIR: /root/.arby
OPENDEX_CERT_PATH: /root/.xud/tls.cert
OPENDEX_RPC_HOST: xud
OPENDEX_RPC_PORT: 28886
MARGIN: 0.04
BASEASSET: ETH
QUOTEASSET: BTC
TEST_CENTRALIZED_EXCHANGE_BASEASSET_BALANCE: 444
TEST_CENTRALIZED_EXCHANGE_QUOTEASSET_BALANCE: 555
```

2020-06-24 12:14 UTC, raladev commented
- specifying though config file is working
- default values are working too
- [ ] specifying through cmd params does not work or maybe i need to pass them in different way.
![Screenshot from 2020-06-24 15-03-14](https://user-images.githubusercontent.com/29906866/85554085-3eb42b80-b62d-11ea-9ad1-30b663eaa0da.png)

2020-06-24 12:29 UTC, erkarl commented
>     * specifying though config file is working
> 
>     * default values are working too
> 
>     * [ ]  specifying through cmd params does not work or maybe i need to pass them in different way.
>       ![Screenshot from 2020-06-24 15-03-14](https://user-images.githubusercontent.com/29906866/85554085-3eb42b80-b62d-11ea-9ad1-30b663eaa0da.png)

@reliveyy any idea why this is not working?

2020-06-24 12:35 UTC, reliveyy submitted a review, later dismissed

2020-06-24 12:35 UTC, reliveyy commented on images/utils/launcher/config/config.py
> +        opt = "arby.test-centralized-baseasset-balance"
```suggestion
        opt = "arby.test_centralized_baseasset_balance"
```

2020-06-24 12:35 UTC, reliveyy commented on images/utils/launcher/config/config.py
> +        opt = "arby.test-centralized-quoteasset-balance"
```suggestion
        opt = "arby.test_centralized_quoteasset_balance"
```

2020-06-24 12:52 UTC, raladev approved these changes

2020-06-24 12:53 UTC, merged