feat: add xud-docker api
ExchangeUnion/xud-docker pull request #726
Opened 2020-09-17 13:50 UTC by reliveyy

This PR adds `--api` optinon for xud-docker-api poc.

### How to test?

```bash
bash xud.sh -b api --api
# select simnet
curl localhost:8080/api/v1/xud/info
```

The default API ports for different networks
1. simnet: 8080
2. testnet: 8081
3. mainnet: 8082

2020-09-17 14:28 UTC, raladev commented
it would be good to change ports for networks because 8080 is default port for web, so lets use it for mainnet.
```
    mainnet: 8080
    testnet: 8081
    testnet: 8082
````

2020-09-17 15:06 UTC, kilrau commented
8080 might actually be used on that box for another webserver, so we should avoid using this port. Following our "+10000 port convention", I'd suggest:
```
    mainnet: 8889
    testnet: 18889
    simnet: 28889
```

2020-09-17 15:25 UTC, raladev commented
- [ ] change default ports - https://github.com/ExchangeUnion/xud-docker/pull/726#issuecomment-694299558
- [ ] proxy container exits if xud is locked when `curl localhost:8080/api/v1/xud/info` , but maybe it is a part of #725
[Screenshot from 2020-09-17 18-22-07](https://user-images.githubusercontent.com/29906866/93492157-2d6c7980-f913-11ea-80e3-30f90802229f.png)

2020-09-17 15:25 UTC, raladev requested changes
Above

2020-09-17 15:50 UTC, kilrau requested changes
Might not be rest convention, but it'll greatly help if keep all original grpc call names as is -> `info` -> `getinfo`. The new lnd rest api does so too: https://api.lightning.community/#v1-getinfo

2020-09-18 07:31 UTC, reliveyy commented
@raladev

>  change default ports

Done.

> proxy container exits if xud is locked when curl localhost:8080/api/v1/xud/info

Fixed. New returns HTTP response `rpc error: code = Unimplemented desc = xud is locked` (text/plain, 500)

> no getbalance and tradehistory urls

WIP.

> no expose-ports cmd parameter for api container
> no api container in --help output
> if it is optional container as arby and others then it would be good to have same naming for parameters -- --api.disabled [true|false] instead of --api

Done. Removed `--api` option and make **proxy** service the same as other options services. 

@kilrau We keep align with LND's RESTful design. The getinfo path changed to `GET /api/v1/xud/getinfo`.

2020-09-18 09:27 UTC, raladev commented
> Fixed. New returns HTTP response `rpc error: code = Unimplemented desc = xud is locked` (text/plain, 500)

May u change status code? 500 - is server err (xud err), locked xud is not err it is just an xud status
Is it possible to change plain text to json ({"err":""})  to support one message format?

2020-09-18 10:54 UTC, raladev requested changes
Above

2020-09-18 12:16 UTC, reliveyy commented
@raladev 

Good suggestion. It's better to keep RESTful API responding JSON for most cases. So I changed error response body to  `{"message": "..."}`. It's like [GitHub API error style](https://developer.github.com/v3/#client-errors). The global 404 and 405 errors are changed like below.

```
{"message": "not found"}
{"message": "method not allowed"}
```

> May u change status code? 500

The error is returned by the grpc library, not returned as a xudrpc.proto response message. It doesn't make sence to return 2xx (OK) or 4xx (client error) for "xud is locked". BTW HTTP code 500 means "Internal Server Error".

> still 8080 8081 8082 are used as default ports

Should be fixed by last commit

> There is proxy in status response when i have no proxy container

Fixing...

2020-09-18 12:21 UTC, reliveyy commented
@raladev @kilrau 

> no getbalance and tradehistory urls

Done.

### getbalance

Get all balances

```
GET /api/v1/xud/getbalance
```

Get single balance

```
GET /api/v1/xud/getbalance/{currency}
```

### tradehistory

Get trade history without limit

```
GET /api/v1/xud/tradehistory
```

Get trade history with limit

```
GET /api/v1/xud/tradehistory?limit=100
```

2020-09-18 12:44 UTC, kilrau commented
Very nice!

2020-09-20 16:28 UTC, raladev commented
GET /api/v1/xud/getbalance:
Rest response
```
{
    orders: {
    BTC: {
    total_balance: "250000000",
    channel_balance: "250000000"
},
    ETH: {
    total_balance: "1499942865",
    channel_balance: "1000000000",
    wallet_balance: "499942865"
},
    LTC: {
    total_balance: "500000000",
    channel_balance: "500000000"
},
    USDT: {
    total_balance: "100000000000",
    channel_balance: "100000000000"
}
}
}
```
getbalance -j response:
```
{
  "balancesMap": [
    [
      "BTC",
      {
        "totalBalance": 250000000,
        "channelBalance": 250000000,
        "pendingChannelBalance": 0,
        "inactiveChannelBalance": 0,
        "walletBalance": 0,
        "unconfirmedWalletBalance": 0
      }
    ],
    [
      "ETH",
      {
        "totalBalance": 1499942865,
        "channelBalance": 1000000000,
        "pendingChannelBalance": 0,
        "inactiveChannelBalance": 0,
        "walletBalance": 499942865,
        "unconfirmedWalletBalance": 0
      }
    ],
    [
      "LTC",
      {
        "totalBalance": 500000000,
        "channelBalance": 500000000,
        "pendingChannelBalance": 0,
        "inactiveChannelBalance": 0,
        "walletBalance": 0,
        "unconfirmedWalletBalance": 0
      }
    ],
    [
      "USDT",
      {
        "totalBalance": 100000000000,
        "channelBalance": 100000000000,
        "pendingChannelBalance": 0,
        "inactiveChannelBalance": 0,
        "walletBalance": 0,
        "unconfirmedWalletBalance": 0
      }
    ]
  ]
}
```
- [ ] change orders to something more suitable;
- if i understood correctly there is no fields with 0 values because of grpc. is it possible to display values with 0 too?

- [ ] limit for tradehistory call does not work;
![Screenshot from 2020-09-20 19-23-30](https://user-images.githubusercontent.com/29906866/93716178-ea124500-fb76-11ea-93d3-5a887bc1270f.png)

- [ ] waiting for this one 'There is proxy in status response when i have no proxy container'.

2020-09-21 05:43 UTC, reliveyy commented
I've noticed in xudrpc.proto there are some http annotations. And they are not follow LND's RESTful desgin. @kilrau @sangaman 

https://github.com/ExchangeUnion/xud/blob/7e5f8ef30a1d01a4405757d4359b827ef86cf750/proto/xudrpc.proto#L117

https://github.com/ExchangeUnion/xud/blob/7e5f8ef30a1d01a4405757d4359b827ef86cf750/proto/xudrpc.proto#L125

2020-09-21 05:51 UTC, reliveyy commented
> if i understood correctly there is no fields with 0 values because of grpc. is it possible to display values with 0 too?

Yes. You are right. It has been fixed by https://github.com/ExchangeUnion/xud-docker-api-poc/commit/1273dcc36471295cb26d7e41f65450e0de8fdefd

> change orders to something more suitable

It's an upstream fix here https://github.com/ExchangeUnion/xud/pull/1909

> limit for tradehistory call does not work;
> waiting for this one 'There is proxy in status response when i have no proxy container'.

Both WIP.

2020-09-21 06:26 UTC, reliveyy commented
> limit for tradehistory call does not work

Fixed by https://github.com/ExchangeUnion/xud-docker-api-poc/commit/4d5091a98fffc01461041e0be2f28381379ac5e7

> waiting for this one 'There is proxy in status response when i have no proxy container'.

Fixed by https://github.com/ExchangeUnion/xud-docker/pull/726/commits/844c103f94614dea91988fb19a3603fb85f690aa

2020-09-21 06:31 UTC, reliveyy commented
There is an xudctl **status** API needs to be done. I think it's better to create another PR to track it individually. Wdyt? @raladev @kilrau

2020-09-21 07:52 UTC, kilrau commented
> I think it's better to create another PR to track it individually. Wdyt?

Sounds good to me!

2020-09-21 07:53 UTC, kilrau commented
So the only thing left here is to test @raladev and get ExchangeUnion/xud#1909 in?

2020-09-21 10:54 UTC, raladev approved these changes

2020-09-21 10:55 UTC, merged