feat: add status api
ExchangeUnion/xud-docker pull request #734
Opened 2020-09-28 13:32 UTC by reliveyy

This PR updates proxy image with `status` branch of [xud-docker-api-poc](https://github.com/exchangeunion/xud-docker-api-poc) which add status API for each services.

### How to test?

```
bash xud.sh -b status-api --proxy.disabled=false
# select testnet
curl -s localhost:18889/api/v1/status
```

You should got a JSON response like

```json
{"arby":"Container missing","bitcoind":"Ready (light mode)","boltz":"Ready","connext":"Ready","geth":"Ready (light mode)","litecoind":"Ready (light mode)","lndbtc":"Ready","lndltc":"Ready","webui":"Container missing","xud":"Waiting for channels"}
```

2020-09-28 19:08 UTC, raladev commented
- what about this point? - # bitcoind/litecoind (syncing percentage adjustment required) - https://github.com/ExchangeUnion/xud-docker-api-poc/pull/1
- [ ] /api/v1/status does not work for simnet because of bitcoind/litecoind/geth
[Screenshot from 2020-09-28 21-01-45](https://user-images.githubusercontent.com/29906866/94474515-6f7ca180-01d6-11eb-93f8-84eaf1e3889d.png)
- [ ] need to add json responses instead of plain text for certain services
[Screenshot from 2020-09-28 21-01-57](https://user-images.githubusercontent.com/29906866/94474603-8c18d980-01d6-11eb-9175-b4c14bb372ee.png)
- [ ] /api/v1/status does not work for testnet if all containers are locked
- [ ] also it would be good to have different responses for disabled clients and for exited (like utils status command works):
if arby was enabled in conf file or cmd param it should be displayed with Container Missing status, but if it was disabled then it should be "Service disabled" status

2020-09-28 19:57 UTC, raladev requested changes
above

2020-09-30 07:09 UTC, reliveyy commented
> what about this point? - # bitcoind/litecoind (syncing percentage adjustment required)

WIP.

> need to add json responses instead of plain text for certain services

https://discordapp.com/channels/547402601885466658/760100087358554113/760573298459017246

> /api/v1/status does not work for testnet if all containers are locked

WIP.

> also it would be good to have different responses for disabled clients and for exited (like utils status command works):
if arby was enabled in conf file or cmd param it should be displayed with Container Missing status, but if it was disabled then it should be "Service disabled" status

Related to https://github.com/ExchangeUnion/xud-docker/pull/741

2020-10-06 15:41 UTC, reliveyy commented
> what about this point? - # bitcoind/litecoind (syncing percentage adjustment required)

Fixed.

> /api/v1/status does not work for testnet if all containers are locked

Now status API fetches statuses in parallel. And errors are converted to status prefixed with "Error:"

2020-10-06 18:05 UTC, raladev commented
- [ ] there is no percentage for litecoind
![Screenshot from 2020-10-06 21-01-04](https://user-images.githubusercontent.com/29906866/95241951-33b98b80-0817-11eb-9adc-d3f9004246d6.png)
- [ ] connext has different status in api and in cli (not good)
- [ ] (not connected with api) webui has ready status when i stopped it (api contains correct status)
- is there a way to handle lnd percentage for neutrino mode too?
```
Syncing light clients:
┌─────────┬─────────────────────────────────────────────────────┐
│ SERVICE │ STATUS                                              │
├─────────┼─────────────────────────────────────────────────────┤
│ lndbtc  │ Syncing 100.00% (1838346/1838342)                   │
└─────────┴─────────────────────────────────────────────────────┘
```

2020-10-07 13:33 UTC, reliveyy commented
> there is no percentage for litecoind

Fixed.

> connext has different status in api and in cli (not good)

WIP.

> (not connected with api) webui has ready status when i stopped it (api contains correct status)

It keeps the same behaviour like xud-docker. And it is a fake "Ready" status. Arby container got fake "Ready" too. And we could improve arby and webui status in a separate PR.

> is there a way to handle lnd percentage for neutrino mode too?

Yes. We could implement this feature in a separate PR.

2020-10-07 15:12 UTC, kilrau commented
> connext has different status in api and in cli (not good)

Agreed, this should be the last thing to be fixed in this PR

2020-10-07 16:17 UTC, reliveyy commented
@raladev 

> connext has different status in api and in cli (not good)

Fixed. (use xucli getinfo connext status first)

2020-10-08 08:17 UTC, kilrau requested changes
- [ ] refactor `https://github.com/ExchangeUnion/xud-docker-api-poc` -> `https://github.com/ExchangeUnion/xud-docker-api` just to keep it clean, even though the redirect works
- [x] JSON response of `status` should be exactly as in the cli, meaning also include the `proxy` status
![image](https://user-images.githubusercontent.com/19181985/95433644-8480cf80-0950-11eb-893d-3d1f3f5f3855.png)

- [ ] change to master once https://github.com/ExchangeUnion/xud-docker-api/pull/1 is merged

2020-10-08 10:03 UTC, reliveyy commented
> refactor https://github.com/ExchangeUnion/xud-docker-api-poc -> https://github.com/ExchangeUnion/xud-docker-api just to keep it clean, even though the redirect works

Done.

> JSON response of status should be exactly as in the cli, meaning also include the proxy status

https://github.com/ExchangeUnion/xud-docker-api/pull/2

> change to master once ExchangeUnion/xud-docker-api#1 is merged

Done.

2020-10-08 10:27 UTC, raladev commented
- [ ] one more status difference (lnd)
![Screenshot from 2020-10-08 13-26-36](https://user-images.githubusercontent.com/29906866/95447175-07625400-096a-11eb-9663-c5161bfc5980.png)

2020-10-08 11:01 UTC, raladev approved these changes

2020-10-08 11:01 UTC, merged