feat: change arby config
ExchangeUnion/xud-docker pull request #740
Opened 2020-09-29 16:42 UTC by erkarl

This PR renames arby's `opendex-baseasset` and `opendex-quoteasset` back to `baseasset` and `quoteasset`.

Additionally, if `cex-baseasset` or `cex-quoteasset` is not specified the value of `baseasset` and `quoteasset` will be used by default.

2020-09-29 16:55 UTC, kilrau requested changes
Minor typo

2020-09-29 16:55 UTC, kilrau commented on images/utils/launcher/config/testnet.conf
> +#cex-base-asset = "" # optional - only needs to be specified when centralized exchange base asset is different from base-asset
```suggestion
#cex-base-asset = "" # optional - only needs to be specified if centralized exchange base asset is different from base-asset
```

2020-09-29 16:55 UTC, kilrau commented on images/utils/launcher/config/testnet.conf
> +#cex-quote-asset = "" # optional - only needs to be specified when centralized exchange base asset is different from base-asset
```suggestion
#cex-quote-asset = "" # optional - only needs to be specified if centralized exchange quote asset is different from quote-asset
```

2020-09-29 16:55 UTC, kilrau commented on images/utils/launcher/config/simnet.conf
> +#cex-base-asset = "" # optional - only needs to be specified when centralized exchange base asset is different from base-asset
```suggestion
#cex-base-asset = "" # optional - only needs to be specified if centralized exchange base asset is different from base-asset
```

2020-09-29 16:55 UTC, kilrau commented on images/utils/launcher/config/simnet.conf
> +#cex-quote-asset = "" # optional - only needs to be specified when centralized exchange base asset is different from base-asset
```suggestion
#cex-quote-asset = "" # optional - only needs to be specified if centralized exchange quote asset is different from quote-asset
```

2020-09-29 16:55 UTC, kilrau commented on images/utils/launcher/config/mainnet.conf
> +#cex-base-asset = "" # optional - only needs to be specified when centralized exchange base asset is different from base-asset
```suggestion
#cex-base-asset = "" # optional - only needs to be specified if centralized exchange base asset is different from base-asset
```

2020-09-29 16:55 UTC, kilrau commented on images/utils/launcher/config/mainnet.conf
> +#cex-quote-asset = "" # optional - only needs to be specified when centralized exchange base asset is different from base-asset
```suggestion
#cex-quote-asset = "" # optional - only needs to be specified if centralized exchange quote asset is different from quote-asset
```

2020-09-29 17:54 UTC, raladev reviewed
```
roma@roma-ThinkPad-X1-Carbon-6th:~/.xud-docker$ bash xud.sh -b feat/config-defaults --arby.disabled false --arby.live-cex true --arby.base-asset USDT --arby.quote-asset DAI --arby.cex Binance --arby.cex-base-asset DAI --arby.cex-quote-asset USDT


LIVE_CEX: true
CEX: BINANCE
LOG_LEVEL: trace
DATA_DIR: /root/.arby
OPENDEX_CERT_PATH: /root/.xud/tls.cert
OPENDEX_RPC_HOST: xud
OPENDEX_RPC_PORT: 28886
MARGIN: 0.02
BASEASSET: USDT
QUOTEASSET: DAI
CEX_BASEASSET: USDT
CEX_QUOTEASSET: DAI
TEST_CENTRALIZED_EXCHANGE_BASEASSET_BALANCE: 1000
TEST_CENTRALIZED_EXCHANGE_QUOTEASSET_BALANCE: 1000
2020-09-29 04:55:40.4040 [Centralized] info: Base asset balance 0.00903446 and quote asset balance 0.00842727
2020-09-29 04:55:41.4141 [Centralized] trace: USDTDAI established connection to wss://stream.binance.com:9443/ws/usdtdai@aggTrade
2020-09-29 04:55:41.4141 [Centralized] trace: heartbeat from USDTDAI socket
2020-09-29 04:55:41.4141 [OpenDEX] trace: Base asset balance 956.81300
```

- [ ] cex param setting does not work

2020-09-29 18:44 UTC, erkarl commented
>     * [ ]  cex param setting does not work

Nice catch! Fixed.

2020-09-30 08:08 UTC, kilrau submitted a review, later dismissed
Tested with:
```
[arby]
base-asset = "ETH"
quote-asset = "BTC"
test-centralized-baseasset-balance = "1000"
test-centralized-quoteasset-balance = "1000"
margin = "0.02"
disabled = false
```
Orders issues as expected.
```
[arby]
cex-base-asset = "ETH"
cex-quote-asset = "BTC"
base-asset = "ETH"
quote-asset = "BTC"
test-centralized-baseasset-balance = "1000"
test-centralized-quoteasset-balance = "1000"
margin = "0.02"
disabled = false
```
Orders issued as expected.
```
[arby]
cex-base-asset = "BTC"
cex-quote-asset = "ETH"
base-asset = "ETH"
quote-asset = "BTC"
test-centralized-baseasset-balance = "1000"
test-centralized-quoteasset-balance = "1000"
margin = "0.02"
disabled = false
```
As expected arby got stuck here and didn't issue any orders since the pair btc/eth doesn't exist on binance:
```
2020-09-30 08:00:59.5959 [Centralized] trace: BTCETH established connection to wss://stream.binance.com:9443/ws/btceth@aggTrade
2020-09-30 08:00:59.5959 [Centralized] trace: heartbeat from BTCETH socket
```
```
[arby]
base-asset = "BTC"
quote-asset = "ETH"
test-centralized-baseasset-balance = "1000"
test-centralized-quoteasset-balance = "1000"
margin = "0.02"
disabled = false
```
Also in this case arby didn't issue orders since BTCETH didn't exist on binance.
```
[arby]
cex-base-asset = "ETH"
cex-quote-asset = "BTC"
base-asset = "BTC"
quote-asset = "ETH"
test-centralized-baseasset-balance = "1000"
test-centralized-quoteasset-balance = "1000"
margin = "0.02"
disabled = false
```
In this last case arby tried to issue orders, but failed since the pair doesn't exist on xud (`2020-09-30 08:07:10.1010 [OpenDEX] warn: 5 NOT_FOUND: trading pair BTC/ETH does not exist. Retrying in 5000ms.`).

2020-09-30 09:28 UTC, kilrau approved these changes

2020-09-30 09:28 UTC, merged