fix: backup location retry answer defualts to yes (#525)
ExchangeUnion/xud-docker pull request #761
Opened 2020-10-28 07:37 UTC by rsercano

resolves #525

2020-10-28 13:09 UTC, reliveyy approved these changes

2020-10-28 13:35 UTC, raladev commented
- [ ] Not sure how to get failed case, but it should be good to change behavior for following case (that i got several times because of typos in the path) to No as default: @rsercano @kilrau 
```
Do you want to create a new xud environment or restore an existing one?
1) Create New
2) Restore Existing
Please choose: 2
Please paste the path to your XUD backup to restore your channel balance, your keys and other historical data: ./sda
Checking files... Path not available. Do you wish to continue WITHOUT restoring channel balance, keys and historical data? [Y/n] 

You are restoring an xud node key and underlying wallets. All will be secured by
a single password provided below.
  
Enter your 24 word mnemonic separated by spaces: 
```

2020-10-28 14:35 UTC, raladev requested changes
above

2020-10-28 14:54 UTC, kilrau commented
Good idea! So one super small addon for Roman's case above @rsercano :
`Do you wish to continue WITHOUT restoring channel balance, keys and historical data? [Y/n]` -> 
`Do you wish to continue WITHOUT restoring channel balance, keys and historical data? [y/N]`

2020-11-03 13:23 UTC, raladev approved these changes

2020-11-03 13:23 UTC, merged