feat(proxy): add ui dashboard app to proxy container
ExchangeUnion/xud-docker pull request #769
Opened 2020-11-07 14:24 UTC by krrprr

This PR adds the functionality of serving the XUD Explorer Dashboard as a web application, independent of the the native Electron app, from the proxy container.

2020-11-09 14:22 UTC, raladev commented
works fine, but we need valid certificate, otherwise browser will throw alert
![Screenshot from 2020-11-09 17-20-57](https://user-images.githubusercontent.com/29906866/98552985-2d07b380-22b0-11eb-9ef5-a9e38128d6bb.png)

2020-11-09 14:23 UTC, raladev requested changes
above

2020-11-09 14:26 UTC, raladev approved these changes

2020-11-09 19:23 UTC, kilrau commented
https://letsencrypt.org/getting-started/

2020-11-09 19:26 UTC, erkarl commented
> https://letsencrypt.org/getting-started/

https://letsencrypt.org/docs/certificates-for-localhost/

2020-11-10 09:06 UTC, reliveyy approved these changes

2020-11-10 09:16 UTC, reliveyy commented
> https://letsencrypt.org/docs/certificates-for-localhost/

@erkarl I have read the guide. You still need to trust your own CA when you try to use TLS with localhost. I think we could leave this certs issue in another PR. And this [mkcert](https://github.com/FiloSottile/mkcert) command will make it easy on Linux/macOS/Windows if you don't want to do multiple mouse clicks.

2020-11-10 09:48 UTC, erkarl approved these changes

2020-11-10 09:48 UTC, merged